name: build
on:
    push:
    branches:
        - master
    pull_request:
jobs:
    build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
        run:
        docker build -t  juice-shop-hcktrckr:latest .
    - name: Run image
        run:
            docker run -d -p 3000:3000 juice-shop-hcktrckr:latest
    - name: Test
        run:
            curl -sSf http://localhost:3000/ > /dev/null
    - name: Stop image
        run:
            docker stop $(docker ps -q --filter ancestor=juice-shop-hcktrckr:latest)
